# Use AlmaLinux 9 as the base image
FROM almalinux:9         

# Install Nginx using DNF package manager
RUN dnf install nginx -y 

# Set the default command to run Nginx in the foreground when the container starts
CMD [ "nginx", "-g", "daemon off;" ]
